server:
  port: 8080
spring:  datasource:    url: jdbc:mysql://127.0.0.1:3306/shiro?useSSL=true&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:  mapper-locations: classpath:mapper/*.xml
  configuration:    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
